[project]
name = "cap-proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "gradio>=0.5.4",
    "langchain>=1.1.3",
    "langchain-openai>=1.1.1",
    "tavily>=1.1.0",
]
